apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    # argocd/app-selector: rht-gitops.com/${{ values.gitops_namespace }}=${{ values.owner }}-${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/source-location: url:https://${{values.git_host}}/${{values.git_destination}}
    backstage.io/techdocs-ref: url:https://${{values.git_host}}/${{values.git_destination}}
    gitlab.com/project-slug: ${{values.gitlab_destination}}
  tags:
    - database
    - postgres
  links: []
spec:
  type: service
  lifecycle: development
  owner: ${{values.owner | dump}}
  providesApis: []
