---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.owner }}-${{ values.component_id }}
  namespace: ${{ values.gitops_namespace }}
  labels:
    rht-gitops.com/${{ values.gitops_namespace }}: ${{ values.owner }}-${{ values.component_id }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: ${{ values.gitops_project }}
  source:
    repoURL: ${{ values.source_repository_gitops }}
    targetRevision: HEAD
    path: ./helm/postgresql
    helm:
      valuesObject:
        nameOverride: ${{ values.component_id }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  ignoreDifferences: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
